export default {
  "Upper Hill": "Upper Hill",
  "Hill District": "Hill District",
  "Anaheim Street": "Anaheim Street",
  "c. 1955": "c. 1955",
  "Marilyn Ware": "Marilyn Ware",
  "c. 1940-1946": "c. 1940-1946",
  "c. 1945-1955": "c. 1945-1955",
  "Harmar Heights": "Harmar Heights",
  "Shriners Way": "Shriners Way",
  "c. 1938-1946": "c. 1938-1946",
  "North Homewood Avenue": "North Homewood Avenue",
  "December 1954": "December 1954",
  "Downtown": "Downtown",
  "Central Northside": "Central Northside",
  "Seventh Avenue": "Seventh Avenue",
  "Smithfield Street": "Smithfield Street",
  "1971": "1971",
  "c. 1962": "c. 1962",
  "c. 1950-1970": "c. 1950-1970",
  "c. 1956": "c. 1956",
  "c. 1946": "c. 1946",
  "c. 1940-1950": "c. 1940-1950",
  "Malvin R. Goode": "Malvin R. Goode",
  "Underwood Street": "Underwood Street",
  "c. 1925-1950": "c. 1925-1950",
  "c. 1943": "c. 1943",
  "Harris Studio": "Harris Studio",
  "c. 1940-1955": "c. 1940-1955",
  "U. S. Navy": "U. S. Navy",
  "c. 1944": "c. 1944",
  "South Oakland": "South Oakland",
  "c. 1955-1970": "c. 1955-1970",
  "1952": "1952",
  "c. 1930-1950": "c. 1930-1950",
  "Barbara Jones": "Barbara Jones",
  "Charles \" Teenie \" Harris": "Charles 'Teenie' Harris",
  "Mount Washington": "Mount Washington",
  "Liberty Avenue": "Liberty Avenue",
  "Henderson": "Henderson",
  "Elmore Street": "Elmore Street",
  "Grant Street": "Grant Street",
  "Fourth Avenue": "Fourth Avenue",
  "c. 1935-1955": "c. 1935-1955",
  "c. 1940-1960": "c. 1940-1960",
  "1966": "1966",
  "1960": "1960",
  "Will Hitchcock": "Will Hitchcock",
  "Clarence Edwards": "Clarence Edwards",
  "Tommy Turrentine": "Tommy Turrentine",
  "c. 1940-1945": "c. 1940-1945",
  "March 1954": "March 1954",
  "Delores Allen": "Delores Allen",
  "Miriam Sharpe Fountain": "Miriam Sharpe Fountain",
  "Roger Thomas": "Roger Thomas",
  "Morris S. Fountain Sr .": "Morris S. Fountain Sr.",
  "Louise Smith": "Louise Smith",
  "Hubert Smith": "Hubert Smith",
  "c. 1955-1975": "c. 1955-1975",
  "Second Avenue": "Second Avenue",
  "c. 1960-1975": "c. 1960-1975",
  "Hazelwood": "Hazelwood",
  "Manchester": "Manchester",
  "South Side Flats": "South Side Flats",
  "Martindale Street": "Martindale Street",
  "1948": "1948",
  "Shadyside": "Shadyside",
  "Walnut Street": "Walnut Street",
  "September 1957": "September 1957",
  "c. 1945-1970": "c. 1945-1970",
  "Frank Bolden": "Frank Bolden",
  "Thomas Logan": "Thomas Logan",
  "March 27-29, 1956": "March 27-29, 1956",
  "c. 1952": "c. 1952",
  "c. 1959": "c. 1959",
  "David L. Lawrence": "David L. Lawrence",
  "c. 1960": "c. 1960",
  "Joe Louis": "Joe Louis",
  "June 22-24, 1955": "June 22-24, 1955",
  "Third Avenue": "Third Avenue",
  "Strip District": "Strip District",
  "Beaver Avenue": "Beaver Avenue",
  "Penn Avenue": "Penn Avenue",
  "East North Avenue": "East North Avenue",
  "Iron City Drive": "Iron City Drive",
  "Federal Street": "Federal Street",
  "May 1940": "May 1940",
  "1951": "1951",
  "James Brown": "James Brown",
  "Herron Hill": "Herron Hill",
  "Elizabeth Youngue": "Elizabeth Youngue",
  "Helen Smith": "Helen Smith",
  "Lucille Cuthbert": "Lucille Cuthbert",
  "Nan Moone Currington": "Nan Moone Currington",
  "Squirrel Hill North": "Squirrel Hill North",
  "Herron Avenue": "Herron Avenue",
  "December 1961": "December 1961",
  "Eunice W. Cook": "Eunice W. Cook",
  "Eunice Cook": "Eunice Cook",
  "Fifth Avenue": "Fifth Avenue",
  "May 1952": "May 1952",
  "Centre Avenue": "Centre Avenue",
  "February 1947": "February 1947",
  "Washington Boulevard": "Washington Boulevard",
  "c. 1945-1950": "c. 1945-1950",
  "Sahara Temple": "Sahara Temple",
  "Robert Lavelle": "Robert Lavelle",
  "Oscar Harris": "Oscar Harris",
  "1957": "1957",
  "Mamie Hamilton": "Mamie Hamilton",
  "Joseph Johnson": "Joseph Johnson",
  "Ann Barnett": "Ann Barnett",
  "Middle Hill": "Middle Hill",
  "Bloomfield": "Bloomfield",
  "Ella Street": "Ella Street",
  "August 1945": "August 1945",
  "Jenkins Arcade": "Jenkins Arcade",
  "Khrushchev": "Khrushchev",
  "August 1959": "August 1959",
  "c. 1935-1945": "c. 1935-1945",
  "Paulson Avenue": "Paulson Avenue",
  "February 1962": "February 1962",
  "William Penn Place": "William Penn Place",
  "Jean Bolden": "Jean Bolden",
  "LeeBrun Johnson": "LeeBrun Johnson",
  "Spring Hill City View": "Spring Hill City View",
  "Lower Lawrenceville": "Lower Lawrenceville",
  "Halket Street": "Halket Street",
  "Charlotte Enty Catlin": "Charlotte Enty Catlin",
  "c. 1954": "c. 1954",
  "1963": "1963",
  "c. 1949": "c. 1949",
  "c. 1957": "c. 1957",
  "Toki Schalk Johnson": "Toki Schalk Johnson",
  "c. 1966-1975": "c. 1966-1975",
  "c. 1938-1945": "c. 1938-1945",
  "c. 1950-1960": "c. 1950-1960",
  "c. 1955-1960": "c. 1955-1960",
  "Fort Riley 's": "Fort Riley 's",
  "South Shore": "South Shore",
  "Lawrenceville": "Lawrenceville",
  "West Station Square Drive": "West Station Square Drive",
  "Butler Street": "Butler Street",
  "July 1942": "July 1942",
  "Pittsburgh Avenue": "Pittsburgh Avenue",
  "1958": "1958",
  "Stanley Williams": "Stanley Williams",
  "1941": "1941",
  "1953": "1953",
  "c. 1945-1975": "c. 1945-1975",
  "East Liberty": "East Liberty",
  "c. 1958": "c. 1958",
  "c. 1950-1975": "c. 1950-1975",
  "Junilla Street": "Junilla Street",
  "Cantrell Road": "Cantrell Road",
  "October 1957": "October 1957",
  "c. 1935-1950": "c. 1935-1950",
  "Bedford Dwellings": "Bedford Dwellings",
  "Homewood South": "Homewood South",
  "Bedford Avenue": "Bedford Avenue",
  "Susquehanna Street": "Susquehanna Street",
  "June 9-11, 1953": "June 9-11, 1953",
  "Robert L. Vann": "Robert L. Vann",
  "c. 1961": "c. 1961",
  "July 1962": "July 1962",
  "1967": "1967",
  "Oliver Mason": "Oliver Mason",
  "Homewood North": "Homewood North",
  "Brushton Avenue": "Brushton Avenue",
  "November 1955": "November 1955",
  "Roland Lucas": "Roland Lucas",
  "R. Walker Storms": "R. Walker Storms",
  "James E. Hawkins": "James E. Hawkins",
  "John R. Caldwell": "John R. Caldwell",
  "Thelma Turner": "Thelma Turner",
  "Alvin Green": "Alvin Green",
  "Olive Cobbs": "Olive Cobbs",
  "John Jackson": "John Jackson",
  "Alton Warren": "Alton Warren",
  "Audrey Smith": "Audrey Smith",
  "Kenneth Harris": "Kenneth Harris",
  "Doris Green": "Doris Green",
  "Margie Lee Floyd": "Margie Lee Floyd",
  "Lois Sims": "Lois Sims",
  "Ernest Summers": "Ernest Summers",
  "Beltzhoover": "Beltzhoover",
  "Central Lawrenceville": "Central Lawrenceville",
  "June 6, 1953": "June 6, 1953",
  "January 1947": "January 1947",
  "Frances Moore": "Frances Moore",
  "1946": "1946",
  "1964": "1964",
  "Max Johnson": "Max Johnson",
  "Living Place": "Living Place",
  "Columbus Avenue": "Columbus Avenue",
  "June 1958": "June 1958",
  "Junyetta Jelks": "Junyetta Jelks",
  "Lincoln-Lemington-Belmar": "Lincoln-Lemington-Belmar",
  "South Hills": "South Hills",
  "Lincoln Avenue": "Lincoln Avenue",
  "West Liberty Avenue": "West Liberty Avenue",
  "Stokes Avenue": "Stokes Avenue",
  "c. 1945-1960": "c. 1945-1960",
  "c. 1953-1965": "c. 1953-1965",
  "1962": "1962",
  "Roland Sawyer": "Roland Sawyer",
  "Earsley Kincaid": "Earsley Kincaid",
  "Forbes Avenue": "Forbes Avenue",
  "June 4, 1955": "June 4, 1955",
  "c. 1945": "c. 1945",
  "January 1945": "January 1945",
  "Thomas J. \" Tommy \" Smith": "Thomas J. 'Tommy' Smith",
  "Harry Bobo": "Harry Bobo",
  "Phipps Conservatory and Botanical Gardens": "Phipps Conservatory and Botanical Gardens",
  "Central Oakland": "Central Oakland",
  "Schenley Drive": "Schenley Drive",
  "1942": "1942",
  "1947": "1947",
  "Everett Utterback": "Everett Utterback",
  "McKinley Park": "McKinley Park",
  "July 1946": "July 1946",
  "North Oakland": "North Oakland",
  "North Dithridge Street": "North Dithridge Street",
  "July 1967": "July 1967",
  "Betty Harris": "Betty Harris",
  "c. 1947": "c. 1947",
  "Mulford Street": "Mulford Street",
  "Wood Street": "Wood Street",
  "1965": "1965",
  "Margaret Bullard": "Margaret Bullard",
  "Ellsworth Avenue": "Ellsworth Avenue",
  "1974": "1974",
  "John Davis": "John Davis",
  "Wylie Avenue": "Wylie Avenue",
  "Elm Street": "Elm Street",
  "August 1951": "August 1951",
  "Henry Ford": "Henry Ford",
  "Josh Gibson": "Josh Gibson",
  "Gloria Golden": "Gloria Golden",
  "Anastas I. Mikoyan": "Anastas I. Mikoyan",
  "C.A. Michel": "C.A. Michel",
  "Stanton Heights": "Stanton Heights",
  "Mossfield Street": "Mossfield Street",
  "Saw Mill Run Boulevard": "Saw Mill Run Boulevard",
  "1959": "1959",
  "Mozelle Thompson": "Mozelle Thompson",
  "North Highland Avenue": "North Highland Avenue",
  "East Carson Street": "East Carson Street",
  "George Barbour": "George Barbour",
  "Bennett Street": "Bennett Street",
  "March 1960": "March 1960",
  "c. 1935-1965": "c. 1935-1965",
  "Squirrel Hill South": "Squirrel Hill South",
  "Forward Avenue": "Forward Avenue",
  "Miller Street": "Miller Street",
  "South 26th Street": "South 26th Street",
  "1972": "1972",
  "McKees Rocks Bottoms": "McKees Rocks Bottoms",
  "Freeport Road": "Freeport Road",
  "Sexton Road": "Sexton Road",
  "August 1946": "August 1946",
  "Patricia": "Patricia",
  "Beatrice Mahaffey": "Beatrice Mahaffey",
  "Earl Harris": "Earl Harris",
  "June 1945": "June 1945",
  "Greene Hearth": "Greene Hearth",
  "Sockwell": "Sockwell",
  "Teenie Harris": "Teenie Harris",
  "Macek Drive": "Macek Drive",
  "April 1954": "April 1954",
  "c. 1925-1945": "c. 1925-1945",
  "Kirkpatrick Street": "Kirkpatrick Street",
  "February 1953": "February 1953",
  "George \" Duke \" Spaulding": "George 'Duke' Spaulding",
  "c. 1950-1959": "c. 1950-1959",
  "Lena Horne": "Lena Horne",
  "Louis Jones": "Louis Jones",
  "Teddy Horne": "Teddy Horne",
  "February 1938": "February 1938",
  "1945": "1945",
  "Beraline Crawford": "Beraline Crawford",
  "Delores Sledge": "Delores Sledge",
  "Rochelle Robinson": "Rochelle Robinson",
  "Paulette Silvers": "Paulette Silvers",
  "Hattie Knox": "Hattie Knox",
  "Ann Perry": "Ann Perry",
  "Gloria Grate 's": "Gloria Grate's",
  "Gloria Golden Grate 's": "Gloria Golden Grate's",
  "Sandra Taylor": "Sandra Taylor",
  "June Rodgers": "June Rodgers",
  "May 1965": "May 1965",
  "c. 1935-1970": "c. 1935-1970",
  "Homer S. Brown": "Homer S. Brown",
  "May 1957": "May 1957",
  "Burrell Johnson": "Burrell Johnson",
  "Phyllis Downing": "Phyllis Downing",
  "Jean Curtis": "Jean Curtis",
  "Pete Jackson": "Pete Jackson",
  "John P. Wesley": "John P. Wesley",
  "William Curtis": "William Curtis",
  "Loretta McCallister": "Loretta McCallister",
  "John Malcus Ellison": "John Malcus Ellison",
  "C. A. Johnson": "C. A. Johnson",
  "Marion Tate": "Marion Tate",
  "Marie Belle Wesley": "Marie Belle Wesley",
  "Ernest H. Wesley": "Ernest H. Wesley",
  "Charles H. Foggie": "Charles H. Foggie",
  "Deane Curtis": "Deane Curtis",
  "September 21, 1946": "September 21, 1946",
  "Maurice Grob": "Maurice Grob",
  "February 1959": "February 1959",
  "c. 1948": "c. 1948",
  "1961": "1961",
  "May - June 1960": "May - June 1960",
  "1939": "1939",
  "Sarah McLawler 's": "Sarah McLawler's",
  "May 26 - 28,1969": "May 26 - 28,1969",
  "c. 1953": "c. 1953",
  "c. 1950-1965": "c. 1950-1965",
  "Frankstown Avenue": "Frankstown Avenue",
  "August 1955": "August 1955",
  "March 1961": "March 1961",
  "1949": "1949",
  "c. 1966": "c. 1966",
  "Daisy Lampkin": "Daisy Lampkin",
  "Regis Bobonis": "Regis Bobonis",
  "Bill Nunn Jr.": "Bill Nunn Jr.",
  "Mal Goode": "Mal Goode",
  "Mmes Mary Douglass": "Mmes Mary Douglass",
  "Delores Talson": "Delores Talson",
  "Earl Francis McGuire": "Earl Francis McGuire",
  "Kathleen Hurst": "Kathleen Hurst",
  "Jesse Holliday": "Jesse Holliday",
  "Andrew McGuire": "Andrew McGuire",
  "Thomas Holliday": "Thomas Holliday",
  "Ada Rickmond": "Ada Rickmond",
  "Bea Harris": "Bea Harris",
  "Kathleen Douglass": "Kathleen Douglass",
  "Geraldine Gilbert": "Geraldine Gilbert",
  "Herbert Willis": "Herbert Willis",
  "Dennis L. Thomas": "Dennis L. Thomas",
  "Mae Thomas": "Mae Thomas",
  "Mary Holloman": "Mary Holloman",
  "Harriet Lewis": "Harriet Lewis",
  "George Anderson": "George Anderson",
  "Lulu Lewis": "Lulu Lewis",
  "Janice Dent": "Janice Dent",
  "Hattie Greene": "Hattie Greene",
  "Audrey McDaniel": "Audrey McDaniel",
  "Joan Bruce": "Joan Bruce",
  "Julia Calloway": "Julia Calloway",
  "Jesse L. Vann": "Jesse L. Vann",
  "Joan Gainer": "Joan Gainer",
  "Delores Anderson": "Delores Anderson",
  "Earl McGuire Sr": "Earl McGuire Sr",
  "Judy Haines": "Judy Haines",
  "Greene Hearthe": "Greene Hearthe",
  "Ann Holliday": "Ann Holliday",
  "James Moore": "James Moore",
  "Louis McGuire": "Louis McGuire",
  "Earl F. McGuire": "Earl F. McGuire",
  "Teresa McGuire": "Teresa McGuire",
  "Odell King": "Odell King",
  "Rebecca Armstrong": "Rebecca Armstrong",
  "October 3, 1953": "October 3, 1953",
  "c. 1940": "c. 1940",
  "James B. Cayce": "James B. Cayce",
  "West 50th Street": "West 50th Street",
  "Maryland Avenue": "Maryland Avenue",
  "June 1956": "June 1956",
  "21st Street": "21st Street",
  "William \" Bill \" Scranton": "William 'Bill' Scranton",
  "William Johnson": "William Johnson",
  "May 1962": "May 1962",
  "A. Leo Weil": "A. Leo Weil",
  "Marshall": "Marshall",
  "c. 1965": "c. 1965",
  "Pittsburgh Parks & Recreation": "Pittsburgh Parks & Recreation",
  "Knoxville": "Knoxville",
  "Bausman Street": "Bausman Street",
  "July 1945": "July 1945",
  "Bigelow Square": "Bigelow Square",
  "June 1950": "June 1950",
  "c. 1951": "c. 1951",
  "Washington Road": "Washington Road",
  "Oberlin Street": "Oberlin Street",
  "Gladys McNairy": "Gladys McNairy",
  "c. 1960-1970": "c. 1960-1970",
  "Henry O. Tanner": "Henry O. Tanner",
  "Thelma Lovette": "Thelma Lovette",
  "1969": "1969",
  "Frank Cepits": "Frank Cepits",
  "Robert \" Bob \" P. French Jr.": "Robert 'Bob' P. French Jr.",
  "Bob French": "Bob French",
  "Washington's Landing": "Washington's Landing",
  "Waterfront Drive": "Waterfront Drive",
  "Tommy Smith": "Tommy Smith",
  "September 1959": "September 1959",
  "Marshall-Shadeland": "Marshall-Shadeland",
  "December 1957": "December 1957",
  "Jacqueline Peeler Cameron": "Jacqueline Peeler Cameron",
  "Robert Joseph Cameron": "Robert Joseph Cameron",
  "Melvin Eugene Peeler": "Melvin Eugene Peeler",
  "Jacqueline Peeler": "Jacqueline Peeler",
  "Bricelyn Street": "Bricelyn Street",
  "37th Street": "37th Street",
  "July 1953": "July 1953",
  "Jessie Vann": "Jessie Vann",
  "Mary Jane Page": "Mary Jane Page",
  "P.L. Prattis": "P.L. Prattis",
  "Rochester Road": "Rochester Road",
  "July 1960": "July 1960",
  "George W. Gaines": "George W. Gaines",
  "Auburn Street": "Auburn Street",
  "May 1939": "May 1939",
  "J. D. Lewis": "J. D. Lewis",
  "Spaulding": "Spaulding",
  "Daisy E. Lampkin": "Daisy E. Lampkin",
  "River Avenue": "River Avenue",
  "PGW Drive": "PGW Drive",
  "Mary Dee": "Mary Dee",
  "c. 1945-1949": "c. 1945-1949",
  "Yellow Cab": "Yellow Cab",
  "Santa Claus": "Santa Claus",
  "December 1951": "December 1951",
  "North Park": "North Park",
  "Allison Park": "Allison Park",
  "Pearce Mill Road": "Pearce Mill Road",
  "Grandview Avenue": "Grandview Avenue",
  "July 1966": "July 1966",
  "George E. Barbour": "George E. Barbour",
  "John L. Clark": "John L. Clark",
  "George Shields": "George Shields",
  "January 1957": "January 1957",
  "c. 1946-1950": "c. 1946-1950",
  "John Smith": "John Smith",
  "J. C. Hairston": "J. C. Hairston",
  "Elsa Harris": "Elsa Harris",
  "1970": "1970",
  "Julia Gaines": "Julia Gaines",
  "George Gaines": "George Gaines",
  "1944": "1944",
  "Wendell Freeland": "Wendell Freeland",
  "c. 1938": "c. 1938",
  "Brookline": "Brookline",
  "Ledlie Street": "Ledlie Street",
  "c. 1959-1970": "c. 1959-1970",
  "James Carey": "James Carey",
  "Olen Land": "Olen Land",
  "Richelieu Davis Jr": "Richelieu Davis Jr",
  "Clifford Kelly": "Clifford Kelly",
  "James Black": "James Black",
  "Vivian Solomon Davis": "Vivian Solomon Davis",
  "Ann Morton": "Ann Morton",
  "Cassandra Powell": "Cassandra Powell",
  "Arthur Coles": "Arthur Coles",
  "Ruth Lee": "Ruth Lee",
  "Donnell Parham": "Donnell Parham",
  "Gwendolyn Johnson": "Gwendolyn Johnson",
  "Richelieu Davis Jr.": "Richelieu Davis Jr.",
  "Vivian Solomon": "Vivian Solomon",
  "Marvin Solomon": "Marvin Solomon",
  "Lathia Gaddie": "Lathia Gaddie",
  "Shirley Gardner": "Shirley Gardner",
  "Juanita Saunders": "Juanita Saunders",
  "Julia Betts": "Julia Betts",
  "R. Frazier": "R. Frazier",
  "Martha Washington 's": "Martha Washington 's",
  "Clarence A. Burrell": "Clarence A. Burrell",
  "Nancy Gaddie": "Nancy Gaddie",
  "Alvin Wiillis": "Alvin Wiillis",
  "Delafield Road": "Delafield Road",
  "July 1957": "July 1957",
  "Matthew Moore": "Matthew Moore",
  "Hugh Cleland": "Hugh Cleland",
  "James O. Dougan": "James O. Dougan",
  "J.B. Cayce": "J.B. Cayce",
  "Churchill Carter": "Churchill Carter",
  "Henry R. Smith": "Henry R. Smith",
  "Marion B. Jordon": "Marion B. Jordon",
  "Smithfield Street Bridge": "Smithfield Street Bridge",
  "Duquesne": "Duquesne",
  "Sixth Avenue": "Sixth Avenue",
  "West Carson Street": "West Carson Street",
  "Webster Avenue": "Webster Avenue",
  "Bryn Mawr Road": "Bryn Mawr Road",
  "January 1956": "January 1956",
  "Patricia Prattis": "Patricia Prattis",
  "November 1961": "November 1961",
  "c. 1945-1965": "c. 1945-1965",
  "Paul F. Jones": "Paul F. Jones",
  "William G. Nunn": "William G. Nunn",
  "Frank Lavelle": "Frank Lavelle",
  "Meadow Street": "Meadow Street",
  "May 1959": "May 1959",
  "Iowa Street": "Iowa Street",
  "May 1958": "May 1958",
  "Reed Street": "Reed Street",
  "Terrace Village": "Terrace Village",
  "June 1962": "June 1962",
  "April 1960": "April 1960",
  "John Writt": "John Writt",
  "Pittsburgh": "Pittsburgh",
  "September 1963": "September 1963",
  "1955": "1955",
  "Fullerton Street": "Fullerton Street",
  "Louis McTurner": "Louis McTurner",
  "October 1961": "October 1961",
  "Point Breeze": "Point Breeze",
  "August 1963": "August 1963",
  "Carver Street": "Carver Street",
  "August 1952": "August 1952",
  "Crawford Grill": "Crawford Grill",
  "Smallman Street": "Smallman Street",
  "George Washington": "George Washington",
  "Charles St.": "Charles St.",
  "Perry South": "Perry South",
  "West Oakland": "West Oakland",
  "Lothrop Street": "Lothrop Street",
  "August 1958": "August 1958",
  "Sabra Washington": "Sabra Washington",
  "Conemaugh Street": "Conemaugh Street",
  "June 10-12, 1954": "June 10-12, 1954",
  "Ramsey Bridges": "Ramsey Bridges",
  "Helen Robinson": "Helen Robinson",
  "David B. Roberts": "David B. Roberts",
  "McFarland Road": "McFarland Road",
  "January 1959": "January 1959",
  "George Little": "George Little",
  "Highland Park": "Highland Park",
  "June 1949": "June 1949",
  "Boulevard of the Allies": "Boulevard of the Allies",
  "Jenkins Street": "Jenkins Street",
  "June 1960": "June 1960",
  "Sarah Kirk": "Sarah Kirk",
  "David Olbum": "David Olbum",
  "Karl O. Jackson": "Karl O. Jackson",
  "South Craig Street": "South Craig Street",
  "W. P. Young": "W. P. Young",
  "Ira Lewis": "Ira Lewis",
  "c. 1950-1955": "c. 1950-1955",
  "1968": "1968",
  "Chauncey Drive": "Chauncey Drive",
  "December 1941": "December 1941",
  "Luther Sewell": "Luther Sewell",
  "c. 1950": "c. 1950",
  "April 1957": "April 1957",
  "c. 1937-1945": "c. 1937-1945",
  "Ira Vann Harris": "Ira Vann Harris",
  "March 1959": "March 1959",
  "c. 1965-1975": "c. 1965-1975",
  "Harold L. Bleakley": "Harold L. Bleakley",
  "North Shore Drive": "North Shore Drive",
  "Lee Bertha West": "Lee Bertha West",
  "Sarah Plowden": "Sarah Plowden",
  "Shirley Mike": "Shirley Mike",
  "North Ridge Drive": "North Ridge Drive",
  "October 1958": "October 1958",
  "November 1941": "November 1941",
  "Betty Tibbs": "Betty Tibbs",
  "Muriel Henry Harrison": "Muriel Henry Harrison",
  "March 1951": "March 1951",
  "March 19-21, 1957": "March 19-21, 1957",
  "November 1956": "November 1956",
  "Edward \" Petey \" Gibson": "Edward 'Petey' Gibson",
  "Ed Gibson": "Ed Gibson",
  "Kenny Durrett": "Kenny Durrett",
  "Willard Fisher": "Willard Fisher",
  "Jake Williams": "Jake Williams",
  "Charley Burley": "Charley Burley",
  "c. 1963": "c. 1963",
  "Betty Love": "Betty Love",
  "Eric Springer": "Eric Springer",
  "Vivian Colbert": "Vivian Colbert",
  "South Highland Avenue": "South Highland Avenue",
  "c. 1930-1955": "c. 1930-1955",
  "Allequippa Street": "Allequippa Street",
  "c. 1939": "c. 1939",
  "Dickey Road": "Dickey Road",
  "William D. McClelland": "William D. McClelland",
  "c. 1941": "c. 1941",
  "William Harris": "William Harris",
  "Leroy Brown": "Leroy Brown",
  "Clarence Bruce": "Clarence Bruce",
  "Mr.and": "Mr.and",
  "Steubenville Pike": "Steubenville Pike",
  "Harry L. Warner": "Harry L. Warner",
  "Lakeview District": "Lakeview District",
  "Allentown": "Allentown",
  "East Warrington Avenue": "East Warrington Avenue",
  "Melwood Avenue": "Melwood Avenue",
  "Potomac Avenue": "Potomac Avenue",
  "January 1940": "January 1940",
  "Leonard Nalls": "Leonard Nalls",
  "October 1954": "October 1954",
  "Bennie Taylor": "Bennie Taylor",
  "November 1946": "November 1946",
  "Midtown": "Midtown",
  "21st Avenue South": "21st Avenue South",
  "Allegheny Center": "Allegheny Center",
  "September 1972": "September 1972",
  "J. A. Williams": "J. A. Williams",
  "Brannon J. Hopson": "Brannon J. Hopson",
  "LeRoy Patrick": "LeRoy Patrick",
  "Race Street": "Race Street",
  "Library Road": "Library Road",
  "c. 1948-1965": "c. 1948-1965",
  "Nelson Harrison": "Nelson Harrison",
  "March 1964": "March 1964",
  "Brownsville Road": "Brownsville Road",
  "Donn Clendenon": "Donn Clendenon",
  "April 1962": "April 1962",
  "California-Kirkbride": "California-Kirkbride",
  "Outer Sunset": "Outer Sunset",
  "Judah Street": "Judah Street",
  "Baum Boulevard": "Baum Boulevard",
  "June 1967": "June 1967",
  "Monticello Street": "Monticello Street",
  "October 30, 1941": "October 30, 1941",
  "Bob Baker": "Bob Baker",
  "September 1956": "September 1956",
  "Linn Washington": "Linn Washington",
  "Warren Watson": "Warren Watson",
  "Joe Golden": "Joe Golden",
  "John Clark": "John Clark",
  "May 1956": "May 1956",
  "March 1962": "March 1962",
  "Marlene Jones": "Marlene Jones",
  "James Slusser": "James Slusser",
  "April 1959": "April 1959",
  "Willie Mays": "Willie Mays",
  "January 1958": "January 1958",
  "June 7-9, 1960": "June 7-9, 1960",
  "Crawford Street": "Crawford Street",
  "Dorothy Jackson": "Dorothy Jackson",
  "Ewart Drive": "Ewart Drive",
  "February 1956": "February 1956",
  "Greenway/Upper Kirby": "Greenway/Upper Kirby",
  "West Alabama Street": "West Alabama Street",
  "c. 1953-1970": "c. 1953-1970",
  "October 1956": "October 1956",
  "Central LA": "Central LA",
  "Camp Street": "Camp Street",
  "South Tennessee Avenue": "South Tennessee Avenue",
  "Watt Street": "Watt Street",
  "Joseph M. Barr": "Joseph M. Barr",
  "February 1961": "February 1961",
  "Beatrice Scott": "Beatrice Scott",
  "Adelaide Biggs": "Adelaide Biggs",
  "Geraldine Smith": "Geraldine Smith",
  "Rebecca West": "Rebecca West",
  "Joan Ryan": "Joan Ryan",
  "Denise Thomas": "Denise Thomas",
  "Jean Holland": "Jean Holland",
  "Geraldine Wouldridge": "Geraldine Wouldridge",
  "Elinor Bowles": "Elinor Bowles",
  "Oneil Bolden": "Oneil Bolden",
  "Kolesque Kalendar": "Kolesque Kalendar",
  "Betty Scott": "Betty Scott",
  "Audrey Moore": "Audrey Moore",
  "Kountry Kaboodle": "Kountry Kaboodle",
  "Janice Pack": "Janice Pack",
  "Jackie Smith": "Jackie Smith",
  "1950": "1950",
  "Harry H. Griggs": "Harry H. Griggs",
  "Vernetta D. Harris Griggs": "Vernetta D. Harris Griggs",
  "Vernetta D. Harris": "Vernetta D. Harris",
  "July 1956": "July 1956",
  "Betty Butler": "Betty Butler",
  "Ethel Ramos Harris": "Ethel Ramos Harris",
  "Hazel Garland": "Hazel Garland",
  "Florence Avenue": "Florence Avenue",
  "September 1962": "September 1962",
  "Lois Simms": "Lois Simms",
  "Jeanine Henry": "Jeanine Henry",
  "Cherokee Street": "Cherokee Street",
  "9th Street": "9th Street",
  "May 1955": "May 1955",
  "Schenley Heights": "Schenley Heights",
  "Beechview": "Beechview",
  "Banksville Road": "Banksville Road",
  "Sixteenth Street Bridge": "Sixteenth Street Bridge",
  "Polk": "Polk",
  "February - March 1962": "February - March 1962",
  "Charles Foggie": "Charles Foggie",
  "Harry Parker": "Harry Parker",
  "Ernestine Parks": "Ernestine Parks",
  "Carl Redwood": "Carl Redwood",
  "Harriet Tubman Guild": "Harriet Tubman Guild",
  "December 1953": "December 1953",
  "Thomas L. West": "Thomas L. West",
  "September 1953": "September 1953",
  "1975": "1975",
  "Deutschstown Historic District": "Deutschstown Historic District",
  "Pressley Street": "Pressley Street",
  "c. 1942": "c. 1942",
  "Harry Fitzgerald": "Harry Fitzgerald",
  "Charles Gaines": "Charles Gaines",
  "Delmont Avenue": "Delmont Avenue",
  "November 1945": "November 1945",
  "Byrd Brown": "Byrd Brown",
  "Lincoln Place": "Lincoln Place",
  "Interboro Avenue": "Interboro Avenue",
  "June 1951": "June 1951",
  "Shirley Smith": "Shirley Smith",
  "Shirley Mason": "Shirley Mason",
  "Lorraine Pearson": "Lorraine Pearson",
  "Darlene Casey": "Darlene Casey",
  "Betty Dunson": "Betty Dunson",
  "Christine Bundridge": "Christine Bundridge",
  "February 1954": "February 1954",
  "Charles Glick": "Charles Glick",
  "Market Street": "Market Street",
  "William P. Young": "William P. Young",
  "William Young": "William Young",
  "Harrisburg Street": "Harrisburg Street",
  "January 1963": "January 1963",
  "Cornell E. Talley": "Cornell E. Talley",
  "Byrd R. Brown": "Byrd R. Brown",
  "Hamilton Avenue": "Hamilton Avenue",
  "c. 1930-1945": "c. 1930-1945",
  "November 1951": "November 1951",
  "William \" Woogie \" Harris": "William 'Woogie' Harris",
  "Simmons": "Simmons",
  "Schenley Park": "Schenley Park",
  "Monongahela Incline": "Monongahela Incline",
  "Elsa Elliott Harris": "Elsa Elliott Harris",
  "Lionel Harris": "Lionel Harris",
  "Crystal Harris": "Crystal Harris",
  "Wandless Street": "Wandless Street",
  "Walt Harper": "Walt Harper",
  "c. 1940-1970": "c. 1940-1970",
  "John J. Wright": "John J. Wright",
  "Charlene Foggie": "Charlene Foggie",
  "James A. Jordon": "James A. Jordon",
  "Marion Bond Jordon": "Marion Bond Jordon",
  "Madeline Sharpe Foggie": "Madeline Sharpe Foggie",
  "John Moore": "John Moore",
  "Walney Road": "Walney Road",
  "Ormsby Avenue": "Ormsby Avenue",
  "Howard Spencer": "Howard Spencer",
  "Francis Street": "Francis Street",
  "Babcock Boulevard": "Babcock Boulevard",
  "Stanwix Street": "Stanwix Street",
  "William G. Nunn Sr .": "William G. Nunn Sr.",
  "Jesse Bell": "Jesse Bell",
  "Ethel Davis": "Ethel Davis",
  "Charles Cooper": "Charles Cooper",
  "Gerald Horsley": "Gerald Horsley",
  "Richard Britton": "Richard Britton",
  "Vivian Mason": "Vivian Mason",
  "Frances Bell": "Frances Bell",
  "Neil Humphries": "Neil Humphries",
  "Robert Pierre Johnson": "Robert Pierre Johnson",
  "James Hampton": "James Hampton",
  "Doris Haines": "Doris Haines",
  "William G. Nunn , Jr.": "William G. Nunn , Jr.",
  "William Golden Nunn Sr .": "William Golden Nunn Sr .",
  "Nancy Reynolds": "Nancy Reynolds",
  "Patty Gore": "Patty Gore",
  "Marguerite Dodson": "Marguerite Dodson",
  "Frances Bell Nunn": "Frances Bell Nunn",
  "August 12, 1950": "August 12, 1950",
  "Wilhelmina": "Wilhelmina",
  "Spring Garden Avenue": "Spring Garden Avenue",
  "Clifton Heights": "Clifton Heights",
  "Hampton Avenue": "Hampton Avenue",
  "c. 1972": "c. 1972",
  "Morris Fountain": "Morris Fountain",
  "Alpha Phi Alpha": "Alpha Phi Alpha",
  "January 1941": "January 1941",
  "Pollard": "Pollard",
  "March - April 1946": "March - April 1946",
  "Brewster Road": "Brewster Road",
  "Ross Street": "Ross Street",
  "Cedar Avenue": "Cedar Avenue",
  "Ile Elegba": "Ile Elegba",
  "Ralph Koger": "Ralph Koger",
  "c. 1973": "c. 1973",
  "May 1941": "May 1941",
  "J. Cephus Ford": "J. Cephus Ford",
  "April 1955": "April 1955",
  "c. 1937": "c. 1937",
  "August 10-18, 1957": "August 10-18, 1957",
  "Frances Peterson": "Frances Peterson",
  "Lillie Tolbert": "Lillie Tolbert",
  "Betty Tate": "Betty Tate",
  "Marilyn Bryant": "Marilyn Bryant",
  "Mary Strother": "Mary Strother",
  "Geraldine Stevens": "Geraldine Stevens",
  "Ruby Thomas": "Ruby Thomas",
  "Brighton Heights": "Brighton Heights",
  "September 1960": "September 1960",
  "May 1954": "May 1954",
  "Evelyn Christian": "Evelyn Christian",
  "Margaret Watson": "Margaret Watson",
  "Juanita Drake": "Juanita Drake",
  "Birdie Dunlap": "Birdie Dunlap",
  "East Station Square Drive": "East Station Square Drive",
  "Harry B. Fitzgerald": "Harry B. Fitzgerald",
  "Mary Lou Williams": "Mary Lou Williams",
  "Station Street": "Station Street",
  "Bill Robinson": "Bill Robinson",
  "Nixon Theater": "Nixon Theater",
  "Bill \" Bojangles \" Robinson": "Bill 'Bojangles' Robinson",
  "Goodwill": "Goodwill",
  "December 1939-January 1940": "December 1939-January 1940",
  "Mount Lebanon Boulevard": "Mount Lebanon Boulevard",
  "December 1952": "December 1952",
  "Myrna Morton": "Myrna Morton",
  "Sharon Revels": "Sharon Revels",
  "Richard Terry": "Richard Terry",
  "Elizabeth Ann Terry": "Elizabeth Ann Terry",
  "Augustus C. Sumpter": "Augustus C. Sumpter",
  "Charles Hill": "Charles Hill",
  "7320 Joshua St.": "7320 Joshua St.",
  "Rosegrain Collins": "Rosegrain Collins",
  "Bunnetta Kemp": "Bunnetta Kemp",
  "John W. Terry": "John W. Terry",
  "Elizabeth Ann": "Elizabeth Ann",
  "James Collins": "James Collins",
  "Betty Ann Davis": "Betty Ann Davis",
  "Gladys Miller": "Gladys Miller",
  "Ewing Batson": "Ewing Batson",
  "I. C. Batson": "I. C. Batson",
  "Ruth Ann Nales": "Ruth Ann Nales",
  "Donna Thompson": "Donna Thompson",
  "Freda Blanton": "Freda Blanton",
  "Benjamin Hawkins": "Benjamin Hawkins",
  "Samuel Johnson Jr.": "Samuel Johnson Jr.",
  "Pocono Mountains": "Pocono Mountains",
  "July 1959": "July 1959",
  "William J. Harvey III": "William J. Harvey III",
  "Genevieve Howard": "Genevieve Howard",
  "Beatrice Jackson": "Beatrice Jackson",
  "Beatrice Williams": "Beatrice Williams",
  "December 1939": "December 1939",
  "c. 1947-1960": "c. 1947-1960",
  "February 1960": "February 1960",
  "James Casey": "James Casey",
  "Brookline Boulevard": "Brookline Boulevard",
  "Charles Bookert": "Charles Bookert",
  "Eugene Youngue": "Eugene Youngue",
  "August 1971": "August 1971",
  "John Watkins": "John Watkins",
  "Robert Watkins": "Robert Watkins",
  "Wilson Hill": "Wilson Hill",
  "Ruth Howard Hill": "Ruth Howard Hill",
  "M. Sharp": "M. Sharp",
  "George Marshall": "George Marshall",
  "Dorothy Marshall": "Dorothy Marshall",
  "Leroy Walker": "Leroy Walker",
  "Alter Howard": "Alter Howard",
  "Bigelow Boulevard": "Bigelow Boulevard",
  "September 1950": "September 1950",
  "Mary Alexander": "Mary Alexander",
  "Louise Davis": "Louise Davis",
  "February - March 1960": "February - March 1960",
  "Norma Malone": "Norma Malone",
  "August - September 1961": "August - September 1961",
  "c. 1920-1940": "c. 1920-1940",
  "February 1950": "February 1950",
  "Kensington Drive": "Kensington Drive",
  "November 1959": "November 1959",
  "Kennedy": "Kennedy",
  "Jackie Robinson": "Jackie Robinson",
  "February 1967": "February 1967",
  "Dorothy Reed": "Dorothy Reed",
  "Paul Bassompierre": "Paul Bassompierre",
  "c. 1946-1966": "c. 1946-1966",
  "Leon Ford": "Leon Ford",
  "Ralph Barnett": "Ralph Barnett",
  "Marshall Johnson": "Marshall Johnson",
  "Cleo Holloway Keith": "Cleo Holloway Keith",
  "April 1946": "April 1946",
  "North Murtland Street": "North Murtland Street",
  "January 1954": "January 1954",
  "January 1951": "January 1951",
  "John Richardson": "John Richardson",
  "Thomas Harold Richardson": "Thomas Harold Richardson",
  "West Highway 80 East": "West Highway 80 East",
  "February 1945": "February 1945",
  "Margaret Lampkin": "Margaret Lampkin",
  "Greentree Road": "Greentree Road",
  "North Craig Street": "North Craig Street",
  "c. 1935-1975": "c. 1935-1975",
  "Green Oak Lane": "Green Oak Lane",
  "Mae Louise Allen": "Mae Louise Allen",
  "Burrows Street": "Burrows Street",
  "Roberto Clemente": "Roberto Clemente",
  "c. 1940-1949": "c. 1940-1949",
  "Dinwiddie Street": "Dinwiddie Street",
  "Pittsburgh Road": "Pittsburgh Road",
  "July 1961": "July 1961",
  "Rose V. Murray": "Rose V. Murray",
  "April 1953": "April 1953",
  "Oliver King": "Oliver King",
  "William Smith": "William Smith",
  "Monongahela River": "Monongahela River",
  "April 1949": "April 1949",
  "Porter W. Phillips": "Porter W. Phillips",
  "Uptown": "Uptown",
  "Cecil Brooks": "Cecil Brooks",
  "Gwendolyn Poinsette": "Gwendolyn Poinsette",
  "April 1956": "April 1956",
  "May 1945": "May 1945",
  "August 1947": "August 1947",
  "Dwight D. Eisenhower": "Dwight D. Eisenhower",
  "October 1952": "October 1952",
  "Goode Pharmacy": "Goode Pharmacy",
  "Frankstown Road": "Frankstown Road",
  "William Goode": "William Goode",
  "Joe Black": "Joe Black",
  "Walter Jones": "Walter Jones",
  "William W. Goode": "William W. Goode",
  "Roy Campanella": "Roy Campanella",
  "October 1953": "October 1953",
  "M.R. Hadley": "M.R. Hadley",
  "R. L. Vann": "R. L. Vann",
  "Thomas J. Smith": "Thomas J. Smith",
  "Charles Jackson": "Charles Jackson",
  "January 1950": "January 1950",
  "Howard Hairston": "Howard Hairston",
  "South Trenton Avenue": "South Trenton Avenue",
  "Martin Kimes": "Martin Kimes",
  "Irving Johnson": "Irving Johnson",
  "Paul Jones": "Paul Jones",
  "Wendell Stanton": "Wendell Stanton",
  "H. H. Gaines": "H. H. Gaines",
  "Wilhelmina Byrd Brown": "Wilhelmina Byrd Brown",
  "Harborside Drive": "Harborside Drive",
  "Lillian Allen": "Lillian Allen",
  "c. 1940-1965": "c. 1940-1965",
  "Omega Psi Phi": "Omega Psi Phi",
  "January 1946": "January 1946",
  "Pocahontas Crews": "Pocahontas Crews",
  "Leona Worthington": "Leona Worthington",
  "Sylvia Yvonne Davis": "Sylvia Yvonne Davis",
  "1954": "1954",
  "Clairton": "Clairton",
  "Pennsylvania Avenue": "Pennsylvania Avenue",
  "Clifford Morrison": "Clifford Morrison",
  "Cliff Street": "Cliff Street",
  "January - February 1953": "January - February 1953",
  "July 1951": "July 1951",
  "Masons": "Masons",
  "Joseph W. Givens": "Joseph W. Givens",
  "West End": "West End",
  "Sterrett Street": "Sterrett Street",
  "Canonsburg": "Canonsburg",
  "6th Street": "6th Street",
  "Donora Street": "Donora Street",
  "Jefferson Drive": "Jefferson Drive",
  "February 1963": "February 1963",
  "Greensburg Pike": "Greensburg Pike",
  "Ray Brown": "Ray Brown",
  "Fort Duquesne Boulevard": "Fort Duquesne Boulevard",
  "April - May 1946": "April - May 1946",
  "Henry Smith": "Henry Smith",
  "c. 1945-1946": "c. 1945-1946",
  "Jane Street": "Jane Street",
  "Woodbine Avenue": "Woodbine Avenue",
  "Rankin": "Rankin",
  "November 1957": "November 1957",
  "Allegheny-West": "Allegheny-West",
  "Western Avenue": "Western Avenue",
  "April - May 1938": "April - May 1938",
  "Jose Gonzales": "Jose Gonzales",
  "Billy Kimes": "Billy Kimes",
  "Hosea Taylor": "Hosea Taylor",
  "Thedrus \" Teddy \" Burch": "Thedrus 'Teddy' Burch",
  "Willett Road": "Willett Road",
  "Holmes": "Holmes",
  "Troy Hill": "Troy Hill",
  "Airport Blvd": "Airport Blvd",
  "May 1969": "May 1969",
  "Marlene Moore": "Marlene Moore",
  "Kathleen Holloway": "Kathleen Holloway",
  "May 1961": "May 1961",
  "c. 1967": "c. 1967",
  "1977": "1977",
  "Homewood West": "Homewood West",
  "June 2, 1941": "June 2, 1941",
  "Mattie Blackwell": "Mattie Blackwell",
  "Marguerite Smart": "Marguerite Smart",
  "Mary E. White": "Mary E. White",
  "Gertrude Russell": "Gertrude Russell",
  "Mildred Johnson": "Mildred Johnson",
  "Regent Square": "Regent Square",
  "7th Street": "7th Street",
  "James McCoy": "James McCoy",
  "Charles Franklin": "Charles Franklin",
  "Three Rivers Heritage Trail": "Three Rivers Heritage Trail",
  "William Hampton": "William Hampton",
  "May 1, 1957": "May 1, 1957",
  "Gaines Funeral Home": "Gaines Funeral Home",
  "c. 1945-1953": "c. 1945-1953",
  "P. L. Prattis": "P. L. Prattis",
  "Richard F. Jones": "Richard F. Jones",
  "Murrel Wynn Jones": "Murrel Wynn Jones",
  "June 1965": "June 1965",
  "Betty Stokes": "Betty Stokes",
  "Commerce Drive": "Commerce Drive",
  "South Pacific Avenue": "South Pacific Avenue",
  "October 1945": "October 1945",
  "c. 1956-1965": "c. 1956-1965",
  "Duquesne Heights": "Duquesne Heights",
  "Market Square": "Market Square",
  "James F. Malone Jr.": "James F. Malone Jr.",
  "February 1958": "February 1958",
  "Willie Stargell": "Willie Stargell",
  "January - February 1946": "January - February 1946",
  "Prothonotary David B. Roberts": "Prothonotary David B. Roberts",
  "Esther Green": "Esther Green",
  "James Jordon": "James Jordon",
  "Gloria Golden Grate": "Gloria Golden Grate",
  "Ruby Young Buchanan": "Ruby Young Buchanan",
  "Nellye Barron": "Nellye Barron",
  "January 1960": "January 1960",
  "Phyllis Pitts": "Phyllis Pitts",
  "April 1958": "April 1958",
  "C.C. Spaulding": "C.C. Spaulding",
  "Robert L. Vann - Spaulding": "Robert L. Vann - Spaulding",
  "Ira F. Lewis": "Ira F. Lewis",
  "October 10, 1943": "October 10, 1943",
  "James Goode": "James Goode",
  "Sewickley": "Sewickley",
  "Edith Smith": "Edith Smith",
  "Eugene Roberts": "Eugene Roberts",
  "Kay Jones": "Kay Jones",
  "South Aiken Avenue": "South Aiken Avenue",
  "c. 1970-1975": "c. 1970-1975",
  "Robert \" Pappy \" Williams": "Robert 'Pappy' Williams",
  "Ezzard Charles": "Ezzard Charles",
  "Peggy Owens": "Peggy Owens",
  "South Braddock Avenue": "South Braddock Avenue",
  "William Battles": "William Battles",
  "Byron Peters": "Byron Peters",
  "Aileen Eckstein Sawyer": "Aileen Eckstein Sawyer",
  "John Brewer": "John Brewer",
  "July 1941": "July 1941",
  "Roland M. Sawyer": "Roland M. Sawyer",
  "Reginald Dixon": "Reginald Dixon",
  "Nate Smith": "Nate Smith",
  "Pat Navarro": "Pat Navarro",
  "c. 1939-1946": "c. 1939-1946",
  "c. 1940-1975": "c. 1940-1975",
  "Morgan Street": "Morgan Street",
  "Broadway Avenue": "Broadway Avenue",
  "February 1941": "February 1941",
  "c. 1954-1956": "c. 1954-1956",
  "East Hills": "East Hills",
  "Wilkinsburg Avenue": "Wilkinsburg Avenue",
  "Leroy Patrick": "Leroy Patrick",
  "April 1952": "April 1952",
  "April - May 1964": "April - May 1964",
  "March - May 1959": "March - May 1959",
  "David Thompkins": "David Thompkins",
  "May 1953": "May 1953",
  "c. 1946-1959": "c. 1946-1959",
  "Chauncey Street": "Chauncey Street",
  "Valerie Stewart": "Valerie Stewart",
  "John Adams": "John Adams",
  "William Penn Hotel": "William Penn Hotel",
  "Charles Smith": "Charles Smith",
  "September - October 1958": "September - October 1958",
  "William Browne": "William Browne",
  "Jimmy Dyer": "Jimmy Dyer",
  "Bobby Jones": "Bobby Jones",
  "Bob Lane": "Bob Lane",
  "Elegants": "Elegants",
  "Walt Mangham": "Walt Mangham",
  "February - March 1968": "February - March 1968",
  "January 1962": "January 1962",
  "George M. Leader": "George M. Leader",
  "Rosedale Street": "Rosedale Street",
  "Tioga Street": "Tioga Street",
  "Robinson Street": "Robinson Street",
  "Cozy Harris": "Cozy Harris",
  "Bentley Drive": "Bentley Drive",
  "Christine Seals": "Christine Seals",
  "Karen Hurst": "Karen Hurst",
  "Charles Palmer": "Charles Palmer",
  "Mary McEinheimer": "Mary McEinheimer",
  "Gladys Stanton": "Gladys Stanton",
  "Adah Lavelle": "Adah Lavelle",
  "Wilnette Young": "Wilnette Young",
  "Alice Woodruff": "Alice Woodruff",
  "Eloise Page": "Eloise Page",
  "Inez E. Hurst": "Inez E. Hurst",
  "Robert Mahoney": "Robert Mahoney",
  "Theodore Steward": "Theodore Steward",
  "Margaret Terry": "Margaret Terry",
  "Ethel Hurst": "Ethel Hurst",
  "Jeanne Poole": "Jeanne Poole",
  "Jacqueline Seals": "Jacqueline Seals",
  "Harry Moore": "Harry Moore",
  "Thomas J. Hurst St.": "Thomas J. Hurst St.",
  "Euzee Mahoney": "Euzee Mahoney",
  "Jeannette Davis": "Jeannette Davis",
  "Augustus Sumpter": "Augustus Sumpter",
  "Marie Simmons": "Marie Simmons",
  "Fannie Wagstaff": "Fannie Wagstaff",
  "Ethel Moore": "Ethel Moore",
  "Ethel Hurst Mahoney": "Ethel Hurst Mahoney",
  "Raymond B. Mahoney": "Raymond B. Mahoney",
  "Margaret Jane Smith": "Margaret Jane Smith",
  "Hallie Turner": "Hallie Turner",
  "Fort Wayne Railroad Bridge": "Fort Wayne Railroad Bridge",
  "Semple Street": "Semple Street",
  "October 1959": "October 1959",
  "Esther Nixon": "Esther Nixon",
  "Lillie Harris": "Lillie Harris",
  "South Side Slopes": "South Side Slopes",
  "Robin Bullard": "Robin Bullard",
  "June 1963": "June 1963",
  "March 1952": "March 1952",
  "1940": "1940",
  "July 1952": "July 1952",
  "March 1958": "March 1958",
  "Finland Street": "Finland Street",
  "February - March 1957": "February - March 1957",
  "Arch Street": "Arch Street",
  "Marlene Stevens": "Marlene Stevens",
  "Barbara Williams": "Barbara Williams",
  "Carole VeLar": "Carole VeLar",
  "Dorothy Williams": "Dorothy Williams",
  "Savannah Ave at Union St": "Savannah Ave at Union St",
  "c. 1941-1945": "c. 1941-1945",
  "William S. Howell": "William S. Howell",
  "August 1957": "August 1957",
  "Henry R. Smith Jr.": "Henry R. Smith Jr.",
  "Main Street": "Main Street",
  "June - July 1969": "June - July 1969",
  "Morningside": "Morningside",
  "Billy Eckstine": "Billy Eckstine",
  "January 1953": "January 1953",
  "c. 1948-1960": "c. 1948-1960",
  "c. 1930-1960": "c. 1930-1960",
  "Gloria Sweeney": "Gloria Sweeney",
  "May 1960": "May 1960",
  "Lois McBride": "Lois McBride",
  "Ruth Butler": "Ruth Butler",
  "Abraham Lincoln": "Abraham Lincoln",
  "April 1945": "April 1945",
  "November 1958": "November 1958",
  "January 1952": "January 1952",
  "Roosevelt Hotel": "Roosevelt Hotel",
  "Charles Harris": "Charles Harris",
  "McKnight Road": "McKnight Road",
  "Kennard Playground": "Kennard Playground",
  "May 29, 1953": "May 29, 1953",
  "Trent Street": "Trent Street",
  "Patrick T. Fagan": "Patrick T. Fagan",
  "Thomas J. Gallagher": "Thomas J. Gallagher",
  "Thomas E. Barrett": "Thomas E. Barrett",
  "c. 1938-1940": "c. 1938-1940",
  "March 25-27, 1958": "March 25-27, 1958",
  "c. 1948-1955": "c. 1948-1955",
  "Alice Thompson": "Alice Thompson",
  "Lois Weaver Watson": "Lois Weaver Watson",
  "1973": "1973",
  "Gay DeHall": "Gay DeHall",
  "Percy A. Garland": "Percy A. Garland",
  "K. Leroy Irvis": "K. Leroy Irvis",
  "October 1960": "October 1960",
  "Newsboys Picnic": "Newsboys Picnic",
  "Carl Davis": "Carl Davis",
  "Robert X. Davenport": "Robert X. Davenport",
  "William Clyde Page": "William Clyde Page",
  "Muhammad Temple": "Muhammad Temple",
  "Donald Williams": "Donald Williams",
  "James D. Drake": "James D. Drake",
  "Bernice Price": "Bernice Price",
  "Lloyd Tobias": "Lloyd Tobias",
  "Pittsburgh Union Station": "Pittsburgh Union Station",
  "October 1950": "October 1950",
  "Mary White": "Mary White",
  "Everett Utterback Sr .": "Everett Utterback Sr.",
  "Richard Jones": "Richard Jones",
  "Ethel Terry": "Ethel Terry",
  "Debbie Gay Evans": "Debbie Gay Evans",
  "Mmes Clyde Johnson": "Mmes Clyde Johnson",
  "C. E. Drummer": "C. E. Drummer",
  "Walter M. Dawson": "Walter M. Dawson",
  "Barbara Jane Edwards": "Barbara Jane Edwards",
  "James Tillman": "James Tillman",
  "John Higgs": "John Higgs",
  "Lonnie Peay": "Lonnie Peay",
  "Leroy Murray": "Leroy Murray",
  "Margaret Kelley": "Margaret Kelley",
  "Connie Cook": "Connie Cook",
  "Marion Burgess": "Marion Burgess",
  "Christian Dior": "Christian Dior",
  "Thelma Fleming": "Thelma Fleming",
  "George Evans": "George Evans",
  "Harry Burgess": "Harry Burgess",
  "Lillian Ruffin": "Lillian Ruffin",
  "Henry Edward": "Henry Edward",
  "Nora Morante": "Nora Morante",
  "Edwards - Lee": "Edwards - Lee",
  "Cordell Lee": "Cordell Lee",
  "Richard Harvey": "Richard Harvey",
  "Harold Curry": "Harold Curry",
  "Barbara Jane Edwards Lee": "Barbara Jane Edwards Lee",
  "Ida Moore": "Ida Moore",
  "Henry Larrance": "Henry Larrance",
  "Harold Caldwell": "Harold Caldwell",
  "Fulmore Lauer": "Fulmore Lauer",
  "Juanita Matthews": "Juanita Matthews",
  "Lucy Bankett": "Lucy Bankett",
  "Bernard Irvin": "Bernard Irvin",
  "Henry Edwards": "Henry Edwards",
  "Ann Garnett Green": "Ann Garnett Green",
  "East 10th Avenue": "East 10th Avenue",
  "September 24, 1955": "September 24, 1955",
  "Erin Street": "Erin Street",
  "January - February 1958": "January - February 1958",
  "Eleanor Roosevelt": "Eleanor Roosevelt",
  "Sylvania Avenue": "Sylvania Avenue",
  "Roosevelt": "Roosevelt",
  "James Davis": "James Davis",
  "Lorenzo Hill": "Lorenzo Hill",
  "Earl V. Hord": "Earl V. Hord",
  "Nellie Barron": "Nellie Barron",
  "Mary Smith": "Mary Smith",
  "Calvin Bartlett": "Calvin Bartlett",
  "Oakwood Street": "Oakwood Street",
  "South Water Street": "South Water Street",
  "June 1953": "June 1953",
  "Melvin Jackson": "Melvin Jackson",
  "September 1952": "September 1952",
  "July 1954": "July 1954",
  "Ahmad Jamal": "Ahmad Jamal",
  "Glen Hazel": "Glen Hazel",
  "Rivermont Drive": "Rivermont Drive",
  "Louise Clark": "Louise Clark",
  "August 1961": "August 1961",
  "Marion Harris": "Marion Harris",
  "Alice Lindsay": "Alice Lindsay",
  "Earl Barnett": "Earl Barnett",
  "Roslyn Lindsay": "Roslyn Lindsay",
  "Helen Douglass": "Helen Douglass",
  "Lydia Taylor": "Lydia Taylor",
  "Helen Phillips": "Helen Phillips",
  "Alyce Lindsay": "Alyce Lindsay",
  "Eloise Robinson": "Eloise Robinson",
  "Murray Avenue": "Murray Avenue",
  "Voyle Parker": "Voyle Parker",
  "February 1964": "February 1964",
  "March 1945": "March 1945",
  "Robert Bolden": "Robert Bolden",
  "William Frederick": "William Frederick",
  "Earl Childs": "Earl Childs",
  "August 1964": "August 1964",
  "Evelyn Anderson": "Evelyn Anderson",
  "c. 1964": "c. 1964",
  "Jimmy Joe Robinson": "Jimmy Joe Robinson",
  "December 1959": "December 1959",
  "Lucinda Harper": "Lucinda Harper",
  "Locust Street": "Locust Street",
  "January 1961": "January 1961",
  "July 1958": "July 1958",
  "October 13, 1962": "October 13, 1962",
  "Sidney Street": "Sidney Street",
  "Queenie Satchell": "Queenie Satchell",
  "Edgar J. Kaufmann": "Edgar J. Kaufmann",
  "Doris Harper": "Doris Harper",
  "Henry Ossawa Tanner": "Henry Ossawa Tanner",
  "Gladys Haines": "Gladys Haines",
  "Esther Summers": "Esther Summers",
  "c. 1941-1942": "c. 1941-1942",
  "June - July 1962": "June - July 1962",
  "Lincoln Park": "Lincoln Park",
  "PPG Place": "PPG Place",
  "Alberta Thompson": "Alberta Thompson",
  "John F. Kennedy": "John F. Kennedy",
  "March 1956": "March 1956",
  "February 1946": "February 1946",
  "Art Rooney Avenue": "Art Rooney Avenue",
  "November 1953": "November 1953",
  "May 31, 1958": "May 31, 1958",
  "October - November 1951": "October - November 1951",
  "Madelyn Hairston": "Madelyn Hairston",
  "Airbrake Avenue": "Airbrake Avenue",
  "Hijar Manor": "Hijar Manor",
  "Bailey W. Williams": "Bailey W. Williams",
  "Margaret Williams": "Margaret Williams",
  "Jayne Lewis Woodson": "Jayne Lewis Woodson",
  "Harriette Lewis": "Harriette Lewis",
  "November 1952": "November 1952",
  "T. J. King": "T. J. King",
  "Greenlee": "Greenlee",
  "Eva Ruth Greenlee": "Eva Ruth Greenlee",
  "Ronald Williams": "Ronald Williams",
  "Stowe Street": "Stowe Street",
  "October 1947": "October 1947",
  "Mary Brown": "Mary Brown",
  "Lemington Avenue": "Lemington Avenue",
  "c. 1947-1965": "c. 1947-1965",
  "Lou Davenport": "Lou Davenport",
  "James T. Wiley": "James T. Wiley",
  "Cornelius D. Scully": "Cornelius D. Scully",
  "Cornelius Scully": "Cornelius Scully",
  "George S. Roberts": "George S. Roberts",
  "June 1944": "June 1944",
  "B. S. Mason": "B. S. Mason",
  "W. D. Petett": "W. D. Petett",
  "September 1961": "September 1961",
  "John H. Morgart": "John H. Morgart",
  "June 1959": "June 1959",
  "Point State Park": "Point State Park",
  "Commonwealth Place": "Commonwealth Place",
  "G. C. Murphy 's": "G. C. Murphy 's",
  "March 1953": "March 1953",
  "Harlem Street": "Harlem Street",
  "Shirley Butler": "Shirley Butler",
  "J.A. Williams": "J.A. Williams",
  "October 1962": "October 1962",
  "July 1970": "July 1970",
  "Martha Tyson": "Martha Tyson",
  "Lois Lee Dorsey": "Lois Lee Dorsey",
  "Tim Stevens": "Tim Stevens",
  "Elizabeth McCombs": "Elizabeth McCombs",
  "Galveston Avenue": "Galveston Avenue",
  "c. 1938-1970": "c. 1938-1970",
  "Jewel Blow": "Jewel Blow",
  "Marjorie Harris": "Marjorie Harris",
  "c. 1949-1960": "c. 1949-1960",
  "c. 1964-1975": "c. 1964-1975",
  "Marshall S. Johnson": "Marshall S. Johnson",
  "Duff Street": "Duff Street",
  "Maude Hawkins": "Maude Hawkins",
  "Billy Conn": "Billy Conn",
  "November - December 1954": "November - December 1954",
  "Lula Bankhead": "Lula Bankhead",
  "Jessie M. Goode": "Jessie M. Goode",
  "William M. Goode": "William M. Goode",
  "Kappa Alpha Osi": "Kappa Alpha Osi",
  "Lester A. White": "Lester A. White",
  "Gaddiel A. Goode": "Gaddiel A. Goode",
  "Aldora Sanders": "Aldora Sanders",
  "Velma Lewis": "Velma Lewis",
  "Clara Browning": "Clara Browning",
  "Barbara E. Ashby": "Barbara E. Ashby",
  "William R. Addison": "William R. Addison",
  "Mary E. Goode": "Mary E. Goode",
  "Hubert House": "Hubert House",
  "August 1962": "August 1962",
  "1956": "1956",
  "Marion Jordon": "Marion Jordon",
  "Ophelia Brown": "Ophelia Brown",
  "Eleanor Morrison": "Eleanor Morrison",
  "Delores Taylor": "Delores Taylor",
  "Thelma Snowden": "Thelma Snowden",
  "Shirley Skinner": "Shirley Skinner",
  "Marie Miller": "Marie Miller",
  "John Johnson": "John Johnson",
  "Willie Williams": "Willie Williams",
  "North Bellefield Avenue": "North Bellefield Avenue",
  "c. 1968": "c. 1968",
  "Curtaineers": "Curtaineers",
  "Fifth Ward": "Fifth Ward",
  "June Eckstine": "June Eckstine",
  "William Penn": "William Penn",
  "September 1967": "September 1967",
  "1938": "1938",
  "Russell Goode": "Russell Goode",
  "Greenfield": "Greenfield",
  "E. L. Smith": "E. L. Smith",
  "April - May 1953": "April - May 1953",
  "James Robinson": "James Robinson",
  "May 1946": "May 1946",
  "c. 1960-1965": "c. 1960-1965",
  "Ralph Brown": "Ralph Brown",
  "January 1966": "January 1966",
  "Joseph Givens": "Joseph Givens",
  "Wilbur Douglass": "Wilbur Douglass",
  "Masonic Way": "Masonic Way",
  "South Main Street": "South Main Street",
  "C.C. Blow": "C.C. Blow",
  "Catherine Wallace": "Catherine Wallace",
  "c. 1941-1944": "c. 1941-1944",
  "A. Polk": "A. Polk",
  "Frances Nunn": "Frances Nunn",
  "Maude Jones": "Maude Jones",
  "Hermitage Street": "Hermitage Street",
  "Frances Pace": "Frances Pace",
  "Leonard Wright": "Leonard Wright",
  "Geraldine Wright": "Geraldine Wright",
  "Harry Waugh": "Harry Waugh",
  "Lindsay": "Lindsay",
  "Coretta Ogburn": "Coretta Ogburn",
  "Buckeystown Pike": "Buckeystown Pike",
  "Mary Jane Mitchell Page": "Mary Jane Mitchell Page",
  "c. 1938-1950": "c. 1938-1950",
  "Marion Bond Jordan": "Marion Bond Jordan",
  "Darrell Kallins": "Darrell Kallins",
  "Robert Smith": "Robert Smith",
  "Middletown": "Middletown",
  "Miriam Gresham": "Miriam Gresham",
  "Franklin Walker Jr.": "Franklin Walker Jr.",
  "Hortense Moran": "Hortense Moran",
  "Kathyn Sedgewick": "Kathyn Sedgewick",
  "Isaac Richardson": "Isaac Richardson",
  "Franklin Walker": "Franklin Walker",
  "Jonathan Walker": "Jonathan Walker",
  "Ronald Pittsman": "Ronald Pittsman",
  "Edward Ford": "Edward Ford",
  "Franklin Walkers Sr .": "Franklin Walkers Sr.",
  "Peter McClary": "Peter McClary",
  "Eddie Dudley": "Eddie Dudley",
  "Fermandy Washington": "Fermandy Washington",
  "Ernest Stevens": "Ernest Stevens",
  "Harry Dobbins": "Harry Dobbins",
  "Lulie Robinson": "Lulie Robinson",
  "Carol Dickerson": "Carol Dickerson",
  "Ruth Mosby": "Ruth Mosby",
  "Long Island City": "Long Island City",
  "Adelaide Street": "Adelaide Street",
  "27th Street": "27th Street",
  "June 28, 1953": "June 28, 1953",
  "June 1941": "June 1941",
  "Morris Fountain Sr .": "Morris Fountain Sr.",
  "Erroll Garner": "Erroll Garner",
  "Bill Nunn Sr .": "Bill Nunn Sr.",
  "July 1964": "July 1964",
  "Adelaide Scott": "Adelaide Scott",
  "John W. Jamerson": "John W. Jamerson",
  "Walter H. S. Parker": "Walter H. S. Parker",
  "Bailey Williams": "Bailey Williams",
  "Henry Primas": "Henry Primas",
  "C. C. Blow": "C. C. Blow",
  "William Jamerson": "William Jamerson",
  "Harriet E. Lewis": "Harriet E. Lewis",
  "Burke Syphas": "Burke Syphas",
  "Jayne Williams": "Jayne Williams",
  "Frederick Abels": "Frederick Abels",
  "Henry Street": "Henry Street",
  "February 19, 1955": "February 19, 1955",
  "Pioneer Avenue": "Pioneer Avenue",
  "March - April 1955": "March - April 1955",
  "Alice Scott": "Alice Scott",
  "March - April 1956": "March - April 1956",
  "Jesse Jackson": "Jesse Jackson",
  "c. 1971": "c. 1971",
  "Robert Turnbull": "Robert Turnbull",
  "Suzanne Patterson": "Suzanne Patterson",
  "Herbert Douglass": "Herbert Douglass",
  "Minerva Williams": "Minerva Williams",
  "Bill Carter": "Bill Carter",
  "Kathryn Bolden": "Kathryn Bolden",
  "John Edwin Brice": "John Edwin Brice",
  "Mary McNeal": "Mary McNeal",
  "Eisenhower": "Eisenhower",
  "August 1956": "August 1956",
  "Paul Thompson": "Paul Thompson",
  "Fairview Park": "Fairview Park",
  "Shetland Street": "Shetland Street",
  "Wilkinsburg": "Wilkinsburg",
  "Beverly Road": "Beverly Road",
  "Perry Street": "Perry Street",
  "c. 1970": "c. 1970",
  "c. 1944-1945": "c. 1944-1945",
  "Vera Thompson": "Vera Thompson",
  "Barbara Thompson": "Barbara Thompson",
  "December 1945": "December 1945",
  "Walt Harper 's": "Walt Harper's Band ",
  "Tiny Irvin": "Tiny Irvin",
  "William Howell": "William Howell",
  "December 1962": "December 1962",
  "Brighton Road": "Brighton Road",
  "James Smith": "James Smith",
  "Nate Harper": "Nate Harper",
  "Jon Morris": "Jon Morris",
  "Billy Lewis": "Billy Lewis",
  "Bert Logan Jr.": "Bert Logan Jr.",
  "West View Park Drive": "West View Park Drive",
  "Fineview": "Fineview",
  "South Dithridge Street": "South Dithridge Street",
  "December 1955": "December 1955",
  "Wilbur C. Douglass": "Wilbur C. Douglass",
  "December 1946": "December 1946",
  "Vankirk Street": "Vankirk Street",
  "Broad Street": "Broad Street",
  "c. 1946-1949": "c. 1946-1949",
  "September 1958": "September 1958",
  "Mary Jean Eaton": "Mary Jean Eaton",
  "Gloria Grate": "Gloria Grate",
  "Holiday Drive": "Holiday Drive",
  "Charles A.": "Charles A.",
  "Ralph Ellison": "Ralph Ellison",
  "Wheeler Street": "Wheeler Street",
  "September - October 1955": "September - October 1955",
  "November 1954": "November 1954",
  "W.D. Petett": "W.D. Petett",
  "Bill Powell": "Bill Powell",
  "Nikita Khrushchev": "Nikita Khrushchev",
  "Perry Township": "Perry Township",
  "South Emerson Avenue": "South Emerson Avenue",
  "September 1946": "September 1946",
  "Larimer Avenue": "Larimer Avenue",
  "Duke Ellington": "Duke Ellington",
  "Nnamdi Azikiwe": "Nnamdi Azikiwe",
  "October 1955": "October 1955",
  "Richard M. Nixon": "Richard M. Nixon",
  "August 1960": "August 1960",
  "Churchill Kohlman": "Churchill Kohlman",
  "c. 1950-1957": "c. 1950-1957",
  "March 1971": "March 1971",
  "November 1962": "November 1962",
  "North Franklin Street": "North Franklin Street",
  "Joyce Sharpe": "Joyce Sharpe",
  "October 1946": "October 1946",
  "December 1969": "December 1969",
  "Harry Walker": "Harry Walker",
  "Fairywood": "Fairywood",
  "Napor Boulevard": "Napor Boulevard",
  "June 1954": "June 1954",
  "Dizzy Gillespie": "Dizzy Gillespie",
  "c. 1969": "c. 1969",
  "Andrea Williams": "Andrea Williams",
  "Roberts Street": "Roberts Street",
  "Clarissa Street": "Clarissa Street",
  "February 1952": "February 1952",
  "Silas Knox": "Silas Knox",
  "Phipps Conservatory": "Phipps Conservatory",
  "November - December 1952": "November - December 1952",
  "June 1961": "June 1961",
  "Frank E. Bolden": "Frank E. Bolden",
  "Plymouth Street": "Plymouth Street",
  "Lorraine McCoad": "Lorraine McCoad",
  "Bill Gambrell": "Bill Gambrell",
  "Gladys Howell": "Gladys Howell",
  "Gerri Walker": "Gerri Walker",
  "Viola Woods": "Viola Woods",
  "Betty Fowler": "Betty Fowler",
  "Ardelle Douglass": "Ardelle Douglass",
  "Sheridan Avenue": "Sheridan Avenue",
  "L. Lawrence": "L. Lawrence",
  "Willa Mae Rice": "Willa Mae Rice",
  "Dearborn Street": "Dearborn Street",
  "Hazel Street": "Hazel Street",
  "April - May 1954": "April - May 1954",
  "Casino Drive": "Casino Drive",
  "October 1967": "October 1967",
  "Toki Schalk": "Toki Schalk",
  "Joe Westray": "Joe Westray",
  "Edward Johnson": "Edward Johnson",
  "Ernest Wainard Warren": "Ernest Wainard Warren",
  "Harriett Ann Johnson": "Harriett Ann Johnson",
  "October 1951": "October 1951",
  "Amity Street": "Amity Street",
  "Gus Greenlee": "Gus Greenlee",
  "Sarah Burney": "Sarah Burney",
  "Gloria Walker": "Gloria Walker",
  "Victor Hereford": "Victor Hereford",
  "Yvonne Jones Kemp": "Yvonne Jones Kemp",
  "Carpenter": "Carpenter",
  "Cab Calloway": "Cab Calloway",
  "Daisy Lloyd": "Daisy Lloyd",
  "Shirley V. Jeffries": "Shirley V. Jeffries",
  "Carl Jefries": "Carl Jefries",
  "Martha Frazier": "Martha Frazier",
  "Ernest Dial": "Ernest Dial",
  "A. L. Solomon": "A. L. Solomon",
  "Bertha Frazier": "Bertha Frazier",
  "Dora Mae Moore": "Dora Mae Moore",
  "William I. Jeffries": "William I. Jeffries",
  "Earl F. Lloyd": "Earl F. Lloyd",
  "Guy Jones": "Guy Jones",
  "Dee Cee Man": "Dee Cee Man",
  "Theodore B. Lloyd": "Theodore B. Lloyd",
  "Thelma Lee McKithen": "Thelma Lee McKithen",
  "Shelia Frazier": "Shelia Frazier",
  "South Shore Riverfront Park": "South Shore Riverfront Park",
  "Webster": "Webster",
  "November 1950": "November 1950",
  "Jody Harris": "Jody Harris",
  "Dolores Parker": "Dolores Parker",
  "Annapolis Avenue": "Annapolis Avenue",
  "Martha Talley": "Martha Talley",
  "c. 1942-1945": "c. 1942-1945",
  "Tom Thumb": "Tom Thumb",
  "Nancy Lee": "Nancy Lee",
  "Wylie Ave": "Wylie Avenue",
  "Elizabeth Ann Terry Collins": "Elizabeth Ann Terry Collins",
  "Joshua Street": "Joshua Street",
  "Lula Howell": "Lula Howell",
  "Water Steps": "Water Steps",
  "August 1953": "August 1953",
  "Martin Luther King": "Martin Luther King",
  "Harry B. Fitzgerald 's": "Harry B. Fitzgerald 's",
  "Bobby Boswell": "Bobby Boswell",
  "Kelly Street": "Kelly Street",
  "Banksville": "Banksville",
  "Brownell Street": "Brownell Street",
  "Joan Bolden": "Joan Bolden",
  "Arthur W. Mitchell": "Arthur W. Mitchell",
  "Boydton and Petersburg Plank Road": "Boydton and Petersburg Plank Road",
  "Upland Street": "Upland Street",
  "c. 1965-1970": "c. 1965-1970",
  "August 1969": "August 1969",
  "October 1969": "October 1969",
  "Robert Lee": "Robert Lee",
  "Mary Gloster": "Mary Gloster",
  "September 1945": "September 1945",
  "September 1969": "September 1969",
  "Walter Rainey": "Walter Rainey",
  "Charles Jones": "Charles Jones",
  "Adelaide Lewis": "Adelaide Lewis",
  "Louise Farrish": "Louise Farrish",
  "Louise Farrish McCullough": "Louise Farrish McCullough",
  "Schoolhouse Road": "Schoolhouse Road",
  "Roy Hamilton": "Roy Hamilton",
  "R. C. Moore": "R. C. Moore",
  "Delores Duncan": "Delores Duncan",
  "Ine Snowden": "Ine Snowden",
  "Oliver Suddeth": "Oliver Suddeth",
  "Dorothy Tibbs": "Dorothy Tibbs",
  "Edward Rose": "Edward Rose",
  "Martha Ann Watts": "Martha Ann Watts",
  "R. Spady": "R. Spady",
  "Glen Lenell Donald": "Glen Lenell Donald",
  "Clarence H. Carr": "Clarence H. Carr",
  "Sally Shinn": "Sally Shinn",
  "Robert Watts": "Robert Watts",
  "Walter Valentine": "Walter Valentine",
  "Harry Durham": "Harry Durham",
  "Martha Ann Watts Carr": "Martha Ann Watts Carr",
  "Alfred Johnson": "Alfred Johnson",
  "Allease Hayes": "Allease Hayes",
  "William Qualls": "William Qualls",
  "Baker Carr": "Baker Carr",
  "Duane Hampton": "Duane Hampton",
  "Katherine Campbell": "Katherine Campbell",
  "Misses Earline": "Misses Earline",
  "Leo Willingham": "Leo Willingham",
  "Zackery Hobbs": "Zackery Hobbs",
  "Christine Guy": "Christine Guy",
  "William Harper": "William Harper",
  "June 1957": "June 1957",
  "Dudley Moore": "Dudley Moore",
  "Gladys Brown": "Gladys Brown",
  "Raab Clothes": "Raab Clothes",
  "October - November 1940": "October - November 1940",
  "Edward Hale": "Edward Hale",
  "Copeland Street": "Copeland Street",
  "March 1965": "March 1965",
  "Deary Street": "Deary Street",
  "Juanita Woods": "Juanita Woods",
  "Rosalind Lindsay": "Rosalind Lindsay",
  "Geraldine Burgia": "Geraldine Burgia",
  "Malvin Goode": "Malvin Goode",
  "Ramond Mahoney": "Ramond Mahoney",
  "Elsie Cap": "Elsie Cap",
  "Olmstead": "Olmstead",
  "Iris Scott": "Iris Scott",
  "Adah Moore Lavelle": "Adah Moore Lavelle",
  "the Herman Scotts": "the Herman Scotts",
  "Wellington Young": "Wellington Young",
  "Jack Crosby Moore": "Jack Crosby Moore",
  "Wooster Square": "Wooster Square",
  "Chalfont Street": "Chalfont Street",
  "East Street": "East Street",
  "July 25, 1942": "July 25, 1942",
  "Elizabeth Reed": "Elizabeth Reed",
  "Howard C. McKinney": "Howard C. McKinney",
  "Orbin Street": "Orbin Street",
  "August - September 1955": "August - September 1955",
  "Ann Baker": "Ann Baker",
  "Grove Road": "Grove Road",
  "Wharton Street": "Wharton Street",
  "August 1944": "August 1944",
  "Beaver Falls": "Beaver Falls",
  "Curtis Haines": "Curtis Haines",
  "Curtis B. Haines": "Curtis B. Haines",
  "December 1956": "December 1956",
  "Alma A. Polk": "Alma A. Polk",
  "September 1954": "September 1954",
  "Northview Heights": "Northview Heights",
  "Alberta Williams": "Alberta Williams",
  "c. 1974": "c. 1974",
  "Helen Prattis": "Helen Prattis",
  "Mary Dee Program": "Mary Dee Program",
  "Station WHOD": "Station WHOD",
  "Roy Ferree": "Roy Ferree",
  "Mary Dee 's": "Mary Dee's",
  "August 1, 1951": "August 1, 1951",
  "Ada Harris": "Ada Harris",
  "Emmett Till": "Emmett Till",
  "McKinley King": "McKinley King",
  "Woody Harris": "Woody Harris",
  "January 1955": "January 1955",
  "Fish Hatchery Road": "Fish Hatchery Road",
  "Fred Staton": "Fred Staton",
  "Northside": "Northside",
  "Joe Robinson": "Joe Robinson",
  "Paquita Sharp": "Paquita Sharp",
  "Aaron Levinson": "Aaron Levinson",
  "Alma Illery": "Alma Illery",
  "Goldie Hamilton": "Goldie Hamilton",
  "Mary Clark": "Mary Clark",
  "Cornell Talley": "Cornell Talley",
  "Claude Morris": "Claude Morris",
  "Miriam Fountain": "Miriam Fountain",
  "Irene Robinson": "Irene Robinson",
  "William \" Woogie \" Harris '": "William 'Woogie' Harris '",
  "December 1958": "December 1958",
  "June 1955": "June 1955",
  "Joseph Barr": "Joseph Barr",
  "October 1965": "October 1965",
  "September - October 1960": "September - October 1960",
  "George Washington Carver": "George Washington Carver",
  "John Thomas": "John Thomas",
  "Jim \" Jimmy \" Swan": "Jim 'Jimmy' Swan",
  "April 1970": "April 1970",
  "May 1951": "May 1951",
  "Jackie Heller": "Jackie Heller",
  "Robert Jones": "Robert Jones",
  "Barbara Ficklin": "Barbara Ficklin",
  "Kennedy - Johnson": "Kennedy - Johnson",
  "Bernice Johnson": "Bernice Johnson",
  "Bernice Johnson Burrell": "Bernice Johnson Burrell",
  "William J. Burrell": "William J. Burrell",
  "March 1957": "March 1957",
  "Jean Willis": "Jean Willis",
  "George Charlton": "George Charlton",
  "Fitzgerald": "Fitzgerald",
  "August - September 1959": "August - September 1959",
  "August 1941": "August 1941",
  "Harold Butler": "Harold Butler",
  "Shady Avenue": "Shady Avenue",
  "Hattie Harris": "Hattie Harris",
  "July - August 1952": "July - August 1952",
  "James Johnson": "James Johnson",
  "Homewood Brushton": "Homewood Brushton",
  "Schenley": "Schenley",
  "Overlook Drive": "Overlook Drive",
  "Alan James": "Alan James",
  "Washington": "Washington",
  "Jefferies": "Jefferies",
  "McTurner": "McTurner",
  "Jubilant Jabberwockies - Pittsburgh": "Jubilant Jabberwockies",
  "Charmaine Jeffries": "Charmaine Jeffries",
  "April - May 1958": "April - May 1958",
  "Allegheny Avenue": "Allegheny Avenue",
  "Nannie West": "Nannie West",
  "Emma Baptist": "Emma Baptist",
  "Juanita Baskin": "Juanita Baskin",
  "Harold Tolliver": "Harold Tolliver",
  "B. H. Logan": "B. H. Logan",
  "James Weldon Johnson": "James Weldon Johnson",
  "Raccoon Creek State Park": "Raccoon Creek State Park",
  "Pennsylvania 18": "Pennsylvania 18",
  "July - August 1941": "July - August 1941",
  "Doris Brown": "Doris Brown",
  "Jim Jordon": "Jim Jordon",
  "Joseph Robinson": "Joseph Robinson",
  "Ridgemont": "Ridgemont",
  "Albany Street": "Albany Street",
  "December 1960": "December 1960",
  "Milwaukee Street": "Milwaukee Street",
  "John Thompson": "John Thompson",
  "Marie Robinson": "Marie Robinson",
  "Calvin King": "Calvin King",
  "August 31, 1943": "August 31, 1943",
  "Lincoln Ave at Lemington Home Drvwy": "Lincoln Ave at Lemington Home Drvwy",
  "Center Street": "Center Street",
  "April 1965": "April 1965",
  "11th Street": "11th Street",
  "Buddy Parker": "Buddy Parker",
  "Morrow Way": "Morrow Way",
  "Strain Behavioral Science": "Strain Behavioral Science",
  "Monongahela Avenue": "Monongahela Avenue",
  "Arthur Burt": "Arthur Burt",
  "Delores Parker": "Delores Parker",
  "Leonard Reed": "Leonard Reed",
  "September 1955": "September 1955",
  "Hilda Logan": "Hilda Logan",
  "Fort Pitt Boulevard": "Fort Pitt Boulevard",
  "Finance Street": "Finance Street",
  "Tom West": "Tom West",
  "South Bellefield Avenue": "South Bellefield Avenue",
  "Eleanor Jones": "Eleanor Jones",
  "Jayne Shelton": "Jayne Shelton",
  "April 1961": "April 1961",
  "Karl Jackson": "Karl Jackson",
  "Wilkins Avenue": "Wilkins Avenue",
  "March 1946": "March 1946",
  "October 1966": "October 1966",
  "Mary Williams": "Mary Williams",
  "Charlotte Carter": "Charlotte Carter",
  "Patricia Jackson": "Patricia Jackson",
  "John Henry Lewis": "John Henry Lewis",
  "E. P. Tunie": "E. P. Tunie",
  "Blackadore Avenue": "Blackadore Avenue",
  "c. 1939-1945": "c. 1939-1945",
  "Cecile Springer": "Cecile Springer",
  "c. 1955-1965": "c. 1955-1965",
  "Maurice Stokes": "Maurice Stokes",
  "Arnold \" Arnie \" Sowell": "Arnold 'Arnie' Sowell",
  "Barbara Robinson": "Barbara Robinson",
  "North Whitfield Street": "North Whitfield Street",
  "Joni Wilson": "Joni Wilson",
  "December 1945 - January 1946": "December 1945 - January 1946",
  "John Wesley AME": "John Wesley AME",
  "Lena Davis": "Lena Davis",
  "Helen Dandridge": "Helen Dandridge",
  "March 1955": "March 1955",
  "Russell Washington": "Russell Washington",
  "Roberto Clemente Bridge": "Roberto Clemente Bridge",
  "George \" Ghost \" Howell": "George 'Ghost' Howell",
  "Isaac Green": "Isaac Green",
  "c. 1960-1961": "c. 1960-1961",
  "1943": "1943",
  "Alex Nelson": "Alex Nelson",
  "East 8th Avenue": "East 8th Avenue",
  "Republic Street": "Republic Street",
  "Clyde Jackson": "Clyde Jackson",
  "East Allegheny": "East Allegheny",
  "East Ohio Street": "East Ohio Street",
  "Airport Road": "Airport Road",
  "John M. Walker": "John M. Walker",
  "Maudelena Johnson": "Maudelena Johnson",
  "Marie Carter Hayes": "Marie Carter Hayes",
  "Idlewild Street": "Idlewild Street",
  "Raymond Harris": "Raymond Harris",
  "Sherwin Williams": "Sherwin Williams",
  "Uncle Sam": "Uncle Sam",
  "Vivian Davidson Hewitt": "Vivian Davidson Hewitt",
  "July - August 1960": "July - August 1960",
  "June 2, 1956": "June 2, 1956",
  "Cheryl \" Tiny \" Harris": "Cheryl 'Tiny' Harris",
  "Dick Ricketts": "Dick Ricketts",
  "May 1949": "May 1949",
  "Barbara Alston": "Barbara Alston",
  "Linda Jackson": "Linda Jackson",
  "Betty Watkins": "Betty Watkins",
  "Dorothy Gloster": "Dorothy Gloster",
  "May-June 1957": "May-June 1957",
  "William Long": "William Long",
  "Billy Taylor": "Billy Taylor",
  "Earl \" Fatha \" Hines": "Earl 'Fatha' Hines",
  "June 20, 1965": "June 20, 1965",
  "Grand Matron": "Grand Matron",
  "Devilliers Street": "Devilliers Street",
  "Hallett Street": "Hallett Street",
  "Liverpool Street": "Liverpool Street",
  "John Brown": "John Brown",
  "Jackie Lewis": "Jackie Lewis",
  "Barbara Stout": "Barbara Stout",
  "Jacks Run": "Jacks Run",
  "Chi Eta Phi": "Chi Eta Phi",
  "December 1950": "December 1950",
  "Robert Head": "Robert Head",
  "Robert Lewis": "Robert Lewis",
  "May 1963": "May 1963",
  "c. 1920-1945": "c. 1920-1945",
  "Polish Hill": "Polish Hill",
  "Julia B. Jones": "Julia B. Jones",
  "Mount Vernon Street": "Mount Vernon Street",
  "Marvin Snowden": "Marvin Snowden",
  "George E. A. Fairley": "George E. A. Fairley",
  "Carl Dickerson": "Carl Dickerson",
  "O'Hara Street": "O'Hara Street",
  "Helen Elizabeth Smith": "Helen Elizabeth Smith",
  "Franklin D. Roosevelt": "Franklin D. Roosevelt",
  "William E.": "William E.",
  "Ruth Buchanan": "Ruth Buchanan",
  "Jacqueline Lewis": "Jacqueline Lewis",
  "Jacqueline \" Jackie \" Lewis": "Jacqueline 'Jackie' Lewis",
  "Toni Bray": "Toni Bray",
  "LuGene Bray": "LuGene Bray",
  "Carol Jones": "Carol Jones",
  "Kay Stokes": "Kay Stokes",
  "Lorenzo R. Adams": "Lorenzo R. Adams",
  "John H. Adams": "John H. Adams",
  "Joseph Watts": "Joseph Watts",
  "November 1969": "November 1969",
  "Yvonne Jones": "Yvonne Jones",
  "Sarah Vaughan": "Sarah Vaughan",
  "Arthur Street": "Arthur Street",
  "January 1973": "January 1973",
  "Charles Walker": "Charles Walker",
  "John J. Kane": "John J. Kane",
  "Ruby Wheeler Woods": "Ruby Wheeler Woods",
  "c. 1948-1956": "c. 1948-1956",
  "Ralph E. Koger": "Ralph E. Koger",
  "Chartiers Avenue": "Chartiers Avenue",
  "Florence Reizenstein": "Florence Reizenstein",
  "Forbes Field": "Forbes Field",
  "October 5, 1960": "October 5, 1960",
  "Bud Saunders": "Bud Saunders",
  "Jerry Sumpter": "Jerry Sumpter",
  "South Park Golf Course": "South Park Golf Course",
  "East Park Drive": "East Park Drive",
  "George Brown": "George Brown",
  "Sherman Adams": "Sherman Adams",
  "George Pitts": "George Pitts",
  "c. 1949-1965": "c. 1949-1965",
  "Harold R. Tolliver": "Harold R. Tolliver",
  "James Jordan": "James Jordan",
  "LaRue Frederick": "LaRue Frederick",
  "Herbert James": "Herbert James",
  "c. 1965-1977": "c. 1965-1977",
  "Viola Sams": "Viola Sams",
  "Hastings Street": "Hastings Street",
  "Robert Frederick": "Robert Frederick",
  "Joan Claudia Bruce Griffin": "Joan Claudia Bruce Griffin",
  "Logan Street": "Logan Street",
  "S. C. Taylor": "S. C. Taylor",
  "Louis Mason": "Louis Mason",
  "Bon Air": "Bon Air",
  "Dapper Dan": "Dapper Dan",
  "Cleo Blakney Jones": "Cleo Blakney Jones",
  "February 1957": "February 1957",
  "George Greenlee": "George Greenlee",
  "Ida Jones": "Ida Jones",
  "Gladys Lawson": "Gladys Lawson",
  "Ethel Littlejohn": "Ethel Littlejohn",
  "Louise Fulton": "Louise Fulton",
  "Paul Williams": "Paul Williams",
  "Lake Drive": "Lake Drive",
  "May 26 - 28,1959": "May 26 - 28,1959",
  "East 13th Avenue": "East 13th Avenue",
  "Thelma Burgess": "Thelma Burgess",
  "Seeburg Wall - Matic": "Seeburg Wall - Matic",
  "Cahow Way": "Cahow Way",
  "Northwest Side": "Northwest Side",
  "Bandera Road": "Bandera Road",
  "Gladys Coffey": "Gladys Coffey",
  "Friendship Avenue": "Friendship Avenue",
  "Hugh Scott": "Hugh Scott",
  "Carol Finch": "Carol Finch",
  "Harold \" Brushes \" Lee": "Harold 'Brushes' Lee",
  "Boyd L. Wilson": "Boyd L. Wilson",
  "Shawnee Street": "Shawnee Street",
  "Louis A. Radelat": "Louis A. Radelat",
  "Erskine Plaza": "Erskine Plaza",
  "Tulsa Street": "Tulsa Street",
  "Lowell Street": "Lowell Street",
  "Richard Nixon": "Richard Nixon",
  "U. S. Marines": "U. S. Marines",
  "Adlai Stevenson": "Adlai Stevenson",
  "Howard B. Stewart": "Howard B. Stewart",
  "Joseph S. Clark": "Joseph S. Clark",
  "Andrew M. Bradley": "Andrew M. Bradley",
  "Baxter Street": "Baxter Street",
  "c. 1946-1960": "c. 1946-1960",
  "Mary Louise Harris": "Mary Louise Harris",
  "George Wein": "George Wein",
  "NAACP": "NAACP",
  "Jean Farrish": "Jean Farrish",
  "Nan Lewis": "Nan Lewis",
  "Bernice Utterback": "Bernice Utterback",
  "Carl Robinson": "Carl Robinson",
  "Akron Way": "Akron Way",
  "Harold Keith": "Harold Keith",
  "John Cundieff": "John Cundieff",
  "Dotty Sandidge": "Dotty Sandidge",
  "Wabash Street": "Wabash Street",
  "J.G. Harris": "J.G. Harris",
  "Nathaniel Dandridge": "Nathaniel Dandridge",
  "George Fairley": "George Fairley",
  "November 1960": "November 1960",
  "c. 1945-1958": "c. 1945-1958",
  "Lois Weaver": "Lois Weaver",
  "Jayne Lewis Williams": "Jayne Lewis Williams",
  "October 1944": "October 1944",
  "Leroy Randall Jr.": "Leroy Randall Jr.",
  "Avalon Street": "Avalon Street",
  "Cliff Mine Road": "Cliff Mine Road",
  "East Swissvale Avenue": "East Swissvale Avenue",
  "Gloria Williams": "Gloria Williams",
  "c. 1935-1960": "c. 1935-1960",
  "Edmonia Stevens": "Edmonia Stevens",
  "Castle Shannon Boulevard": "Castle Shannon Boulevard",
  "c. 1946-1955": "c. 1946-1955",
  "Gerald Fox": "Gerald Fox",
  "c. 1960-1969": "c. 1960-1969",
  "November - December 1945": "November - December 1945",
  "February 1955": "February 1955",
  "Ernestine Holloway": "Ernestine Holloway",
  "Ross Park Mall Drive": "Ross Park Mall Drive",
  "Park Avenue": "Park Avenue",
  "Martin Luther King Jr.": "Martin Luther King Jr.",
  "Arnie Sowell": "Arnie Sowell",
  "Cecelia Trower": "Cecelia Trower",
  "Fred Gladney": "Fred Gladney",
  "Chesterfield Road": "Chesterfield Road",
  "Horace Turner": "Horace Turner",
  "Jim Brown": "Jim Brown",
  "Ethel Chavis": "Ethel Chavis",
  "Birmingham Avenue": "Birmingham Avenue",
  "Al Johnson": "Al Johnson",
  "Coraopolis": "Coraopolis",
  "Edna Anderson": "Edna Anderson",
  "Bower Hill Road": "Bower Hill Road",
  "Rod Doss": "Rod Doss",
  "Earl Hord": "Earl Hord",
  "James A. Cox": "James A. Cox",
  "John Williams": "John Williams",
  "c. 1941-1946": "c. 1941-1946",
  "Pete Dimperio": "Pete Dimperio",
  "Edythe Smith Perkins": "Edythe Smith Perkins",
  "October 1941": "October 1941",
  "Thaddeus \" Thad \" Mosley": "Thaddeus 'Thad' Mosley",
  "George F. Brown": "George F. Brown",
  "Juanita Page": "Juanita Page",
  "Veola Farrish Moon": "Veola Farrish Moon",
  "Jessie Vann 's": "Jessie Vann's",
  "Margaret Nelson": "Margaret Nelson",
  "Betty Culberson": "Betty Culberson",
  "Florence Hutchinson": "Florence Hutchinson",
  "Mahon Street": "Mahon Street",
  "Virginia Jones": "Virginia Jones",
  "Ligonier Street": "Ligonier Street",
  "May 1966": "May 1966",
  "Lowrie Street": "Lowrie Street",
  "William Jackson": "William Jackson",
  "Charles P. Pernell": "Charles P. Pernell",
  "Rosemarie Lawrence": "Rosemarie Lawrence",
  "Charlie Parker": "Charlie Parker",
  "Harvey Adams": "Harvey Adams",
  "Thelma Street": "Thelma Street",
  "Mildred Brown": "Mildred Brown",
  "Lewis Scott": "Lewis Scott",
  "William Robinson": "William Robinson",
  "Savoy Ballroom": "Savoy Ballroom",
  "Thomas Barton": "Thomas Barton",
  "Thomas L. West Sr .": "Thomas L. West Sr .",
  "James F. Malone": "James F. Malone",
  "Bryant Street": "Bryant Street",
  "Robert Williams": "Robert Williams",
  "Buena Vista Street": "Buena Vista Street",
  "D. W. Bass": "D. W. Bass",
  "William Davis": "William Davis",
  "Humber Way": "Humber Way",
  "Loendi": "Loendi",
  "Arlington Avenue": "Arlington Avenue",
  "Noblestown Road": "Noblestown Road",
  "Lyda Jo Boswell": "Lyda Jo Boswell",
  "Richard Reed": "Richard Reed",
  "Emerson Street": "Emerson Street",
  "Little Genevieve": "Little Genevieve",
  "Myrtle Wilson": "Myrtle Wilson",
  "Dewey Taylor": "Dewey Taylor",
  "Boots Swann": "Boots Swann",
  "Froshine Stewart": "Froshine Stewart",
  "November 1939": "November 1939",
  "Sara Vaughn": "Sara Vaughn",
  "O.M. Walton": "O.M. Walton",
  "Joe Walcott": "Joe Walcott",
  "Wynona Farrish Graves": "Wynona Farrish Graves",
  "William Cuthbert": "William Cuthbert",
  "Apple Street": "Apple Street",
  "Robert Brown": "Robert Brown",
  "Dolores Stanton": "Dolores Stanton",
  "Louise Ford": "Louise Ford",
  "August - September 1957": "August - September 1957",
  "Point Breeze North": "Point Breeze North",
  "Beverly Butler": "Beverly Butler",
  "Raymond Jones": "Raymond Jones",
  "Dorothy Anderson": "Dorothy Anderson",
  "Louis Mason Jr.": "Louis Mason Jr.",
  "April - May 1945": "April - May 1945",
  "June 1946": "June 1946",
  "Arthur Perkins Jr.": "Arthur Perkins Jr.",
  "Evelyn Donald": "Evelyn Donald",
  "Jeanne Yvonne Adams Daniels": "Jeanne Yvonne Adams Daniels",
  "Joseph W. Daniels": "Joseph W. Daniels",
  "Jeanne Yvonne Adams": "Jeanne Yvonne Adams",
  "Mable Adams": "Mable Adams",
  "Eugene Barkley": "Eugene Barkley",
  "Nan Moon Currington": "Nan Moon Currington",
  "Sadie E. Harris": "Sadie E. Harris",
  "Joseph Wayne Daniels": "Joseph Wayne Daniels",
  "Burl J. Moone III": "Burl J. Moone III",
  "Cornelius Harris III": "Cornelius Harris III",
  "Alfred J. Daniels Sr .": "Alfred J. Daniels Sr.",
  "Laura Gale Adams": "Laura Gale Adams",
  "Carl Morris": "Carl Morris",
  "Thurgood Marshall": "Thurgood Marshall",
  "October 1938": "October 1938",
  "John Jones": "John Jones",
  "Henderson Street": "Henderson Street",
  "Charles Page": "Charles Page",
  "Betty Jean Williams": "Betty Jean Williams",
  "June 1966": "June 1966",
  "Charles \" Chuck \" Reeves": "Charles 'Chuck' Reeves",
  "William R. Lowry": "William R. Lowry",
  "Charles Hinton": "Charles Hinton",
  "Hotel Sherwyn": "Hotel Sherwyn",
  "Beverly Scott": "Beverly Scott",
  "Janet Thompson": "Janet Thompson",
  "David Lawrence": "David Lawrence",
  "Marjorie Jackson": "Marjorie Jackson",
  "Dorothy Johnson": "Dorothy Johnson",
  "A.J. Allen": "A.J. Allen",
  "Harold L. Tolliver": "Harold L. Tolliver",
  "Gilmore Industrial Boulevard": "Gilmore Industrial Boulevard",
  "Earl Johnson": "Earl Johnson",
  "Reva George": "Reva George",
  "Foster Square": "Foster Square"
}